services:
  database:
    image: mysql:8.0
    container_name: database
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
    ports:
      - "3305:3306"
    networks:
      - MZ

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
    command: >
      sh -c "sleep 10 &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --no-input &&
            python manage.py runserver 0.0.0.0:8000"
    tty: true
    networks:
      - MZ

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - MZ

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - backend
    networks:
      - MZ

  celery:
    container_name: celery
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    command: sh -c "celery -A rumz worker -l info"

    networks:
      - MZ
    depends_on:
      - rabbitmq
      - backend

networks:
  MZ:
    driver: bridge
