 services:
    backend_test:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend_test
      ports:
        - "8000:8000"
      command: >
        sh -c "sleep 10 &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py test "
      tty: true
