 services:
    backend_test:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend_test
      ports:
        - "8000:8000"
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_HOST: ${DB_HOST}
        MYSQL_PORT: ${DB_PORT}
      command: >
        sh -c "sleep 10 &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py test"
      tty: true
