global:
  scrape_interval: 15s

  external_labels:
    monitor: 'rumz_monitor'

alerting:
	alertmanagers:
	- static_configs:
	  - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'cAdvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'django-blue'
    static_configs:
    - targets: ['backend-blue:8000']
  - job_name: 'django-green'
    static_configs:
    - targets: ['backend-green:8001']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']