# Generated by Django 5.1a1 on 2024-07-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterid', models.AutoField(primary_key=True, serialize=False)),
                ('charactername', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeTime',
            fields=[
                ('timeid', models.AutoField(primary_key=True, serialize=False)),
                ('episodetime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('workerid', models.AutoField(primary_key=True, serialize=False)),
                ('workerlocation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.work')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episodeid', models.AutoField(primary_key=True, serialize=False)),
                ('episodecontent', models.CharField(max_length=200)),
                ('episodetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.episodetime')),
            ],
        ),
        migrations.CreateModel(
            name='ChatEpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.episode')),
            ],
            options={
                'unique_together': {('room', 'episode')},
            },
        ),
    ]
