# Generated by Django 4.2.3 on 2024-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('stability', models.IntegerField(max_length=20)),
                ('similarity', models.IntegerField(max_length=20)),
                ('style', models.IntegerField(max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.character')),
            ],
        ),
    ]
