# Generated by Django 5.1a1 on 2024-07-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_character_characterscript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='characterid',
            new_name='character_id',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='charactername',
            new_name='character_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='characterscript',
            new_name='character_script',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='roomid',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episodecontent',
            new_name='episode_content',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episodeid',
            new_name='episode_id',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episodetime',
            new_name='episode_time',
        ),
        migrations.RenameField(
            model_name='episodetime',
            old_name='episodetime',
            new_name='episode_time',
        ),
        migrations.RenameField(
            model_name='episodetime',
            old_name='timeid',
            new_name='time_id',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='workerid',
            new_name='worker_id',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='workerlocation',
            new_name='worker_location',
        ),
    ]
