# Generated by Django 5.1a1 on 2024-07-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_mz_rank_alter_chatroom_character_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='mz_rank',
            new_name='mz_percent',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.character'),
        ),
    ]
