# Generated by Django 5.1a1 on 2024-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
