# Generated by Django 5.1a1 on 2024-07-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usernumber',
            new_name='user_number',
        ),
    ]
